name: Scala CI

on:
 push:
   branches: [ main, development]
 pull_request:
   branches: [ main, development]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4

   - name: Install sbt
     uses: coursier/setup-action@v1
     with:
       apps: sbt
  

   - name: Set up JDK 24
     uses: actions/setup-java@v3
     with:
       java-version: '24'
       distribution: 'temurin'
   
   - name: Run tests with coverage
     run: sbt clean coverage test coverageReport coverageAggregate coveralls
     env:
       COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

   - name: Git checkout (merge)
     uses: actions/checkout@v3
     if: github.event_name != 'pull_request'
     with:
       fetch-depth: 0

   - name: Git checkout (PR)
     uses: actions/checkout@v3
     if: github.event_name == 'pull_request'
     with:
       fetch-depth: 0
       # see: https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
       ref: ${{ github.event.pull_request.head.sha }}

   - name: Run tests
     run: sbt clean coverage test

   - name: Upload coverage data to Coveralls
     run: sbt coverageReport coveralls
     env:
       COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}